# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 12:29
from __future__ import unicode_literals

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('days', models.IntegerField(verbose_name='Срок цели')),
                ('weekdays', models.IntegerField(verbose_name='Дни отчетов')),
                ('price_words', models.TextField(max_length=100, verbose_name='Цена слова')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала цели')),
                ('end', models.DateTimeField(verbose_name='Дата окончания')),
                ('status', models.TextField(default='in-process', max_length=10, verbose_name='Статус')),
                ('likes_amount', models.IntegerField(default=0, verbose_name='Число лайков')),
                ('success_comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Комментарий к выполненной цели')),
                ('fail_comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Комментарий к невыполненной цели')),
            ],
            options={
                'verbose_name_plural': 'Цели пользователей',
                'verbose_name': 'Цель пользователя',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=400, null=True, verbose_name='Текст поста')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=base.models.upload_location_for_post, verbose_name='Изображения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name_plural': 'Посты пользователей',
                'verbose_name': 'Пост пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('more_info', models.TextField(blank=True, default='', max_length=140, null=True, verbose_name='Дополнительная информация')),
                ('web_site', models.URLField(blank=True, default='', max_length=100, null=True, verbose_name='Сайт')),
                ('avatar', imagekit.models.fields.ProcessedImageField(upload_to=base.models.upload_location, verbose_name='Аватар')),
                ('statistics', models.TextField(default='0,0,0', max_length=14, verbose_name='Статистика')),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarks', to='base.Goal', verbose_name='Закладки')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_name', to='base.UserProfile', verbose_name='Подписчики')),
                ('following', models.ManyToManyField(blank=True, related_name='following_name', to='base.UserProfile', verbose_name='Подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
                'verbose_name': 'Профиль пользователя',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='base.UserProfile', verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.UserProfile', verbose_name='Пользователь'),
        ),
    ]
